### ISSUE TITLE
release gitrel?

### ISSUE THREAD

**Issue by StevenACoffman** [axllent/upload2dav#1]
Hi! This was useful, but it depends on `axllent/gitrel`, which appears to be private. Is that something you can release?

**Comment by axllent** [comment]
Thanks @StevenACoffman, that's a complete blunder on my part - `axllent/gitrel` was replaced (and deleted) by `axllent/ghru` and I completely overlooked the fact that this project still used it. I have updated the source code (minor changes) and pushed a new release. Thanks for the feedback!

**Comment by StevenACoffman** [comment]
ghru is pretty neat! I'll check it out. I wonder if it works for private repos? 🤔

**Comment by axllent** [comment]
@StevenACoffman No, unfortunately it does not support private repos, only public ones.
