### ISSUE TITLE
upload giving error

### ISSUE THREAD

**Issue by muralikodali** [axllent/upload2dav#2]
uploading file to nextcloud server giving following error :  

```
$ upload2dav README.md
Error: MkdirAll /Uploads/: 200
```

**Comment by axllent** [comment]
This is strange and I'm not able to replicate it on my end. I have edited the `UploadDir` to several things (that doesn't already exist) and it is automatically created.

Are you sure you have set the correct webdav URL for your Nextcloud server?  This is typically something like `https://<yourdomain>/remote.php/webdav/` ?

**Comment by muralikodali** [comment]
for server address, i have added base url of server.

adding "remote.php/webdav" to the base url solved the problem.

thanks for your suggestion.

it will be helpful, if you put the suggestion in the README.

**Comment by axllent** [comment]
Glad it worked, and thank you for the suggestion. I have added something to the README relating to this.
